name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  CI:
    if: ${{ !contains(toJson(github.event.pull_request.labels), '[Skip] CI') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker compose build

      #- name: Docker Run
      #  run: docker compose up

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Run
        run: docker compose push