name: CI

on:
  push:
    branches:
      - develop

jobs:
  CI:
    if: ${{ !contains(toJson(github.event.pull_request.labels), '[Skip] CI') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login GitHub Registry
        uses: docker/login-action@v1.13.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ghcr.io/aki-0421/esrgan-container